# Generated by Django 3.0.11 on 2021-01-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Votre nom'),
        ),
    ]
