# Generated by Django 3.0.11 on 2021-01-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0004_auto_20210104_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='None', upload_to=''),
        ),
    ]
