# Generated by Django 3.0.11 on 2021-01-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0005_auto_20210104_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
