# Generated by Django 3.0.11 on 2021-01-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0004_auto_20210104_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('complete_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
    ]
