# Generated by Django 3.0.11 on 2021-01-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0006_auto_20210107_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fb_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='ist_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='tw_link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
