# Generated by Django 3.0.11 on 2021-01-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0010_auto_20210107_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='author',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter',
        ),
    ]
