# Generated by Django 3.0.11 on 2021-01-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0011_auto_20210107_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
