# Generated by Django 3.0.11 on 2021-01-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0012_author_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='facebook',
        ),
    ]
