# Generated by Django 3.0.11 on 2021-01-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0017_auto_20210107_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fb_link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ist_link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='tw_link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='_blog.Author'),
        ),
    ]
