# Generated by Django 3.0.11 on 2021-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0018_auto_20210107_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fb_link',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='ist_link',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='tw_link',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
