# Generated by Django 3.0.11 on 2021-01-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0020_auto_20210107_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fb_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='ist_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='tw_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
