# Generated by Django 3.0.11 on 2021-01-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0021_auto_20210107_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='author',
            name='ist_link',
        ),
        migrations.RemoveField(
            model_name='author',
            name='tw_link',
        ),
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
