# Generated by Django 3.0.11 on 2021-01-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0022_auto_20210107_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.TextField(max_length=2000)),
                ('about', models.TextField(max_length=1000)),
            ],
        ),
    ]
