# Generated by Django 3.0.11 on 2021-01-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0024_auto_20210108_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField(max_length=2000)),
                ('about_text', models.TextField(max_length=1000)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('about_text',),
            },
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
