# Generated by Django 3.0.11 on 2021-01-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_blog', '0027_auto_20210108_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
